# https://school.programmers.co.kr/learn/courses/30/lessons/59412

SELECT
    HOUR(DATETIME) AS HOUR,
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING 9 <= HOUR AND HOUR <= 19
ORDER BY HOUR